export const customerTranslations = {
  ar: {
    appName: "منيو فلو", table: "طاولة رقم", welcomeMessage: "أهلاً بك في مطعمنا!", all: "الكل", burgers: "برجر", pizza: "بيتزا", appetizers: "مقبلات", salads: "سلطات", main: "وجبات رئيسية", desserts: "حلويات", drinks: "مشروبات", specialNote: "ملاحظة خاصة على الوجبة...", addToCart: "أضف للسلة", checkout: "إتمام الطلب", deliveryDetails: "بيانات التوصيل", enterCustomerName: "الاسم الكامل / عنوان الطلب", enterAddress: "العنوان بالتفصيل", enterPhone: "رقم الهاتف", confirmOrder: "تأكيد الطلب", aiAssistantTitle: "مساعد MenuFlow الذكي", aiInputPlaceholder: "هل المكونات طبيعية؟ اسأل الذكاء الاصطناعي...", send: "إرسال", aiErrorMessage: "عذراً، حدث خطأ أثناء الاتصال بالمساعد.", currentOrderStatus: "حالة الطلب الحالية", howWasExperience: "كيف كانت تجربتك معنا؟", yourFeedback: "اكتب ملاحظاتك وتقييمك هنا...", sendReview: "إرسال التقييم", thankYouReview: "شكراً لك! تم استلام تقييمك بنجاح.", stagePending: "استلام", stagePreparing: "تحضير", stageReady: "جاهز", stagePaid: "دفع", statusPendingMsg: "تم استلام طلبك بنجاح!", statusPreparingMsg: "جاري تحضير طلبك بصلصة الحب... 👨‍🍳", statusReadyMsg: "طلبك جاهز تماماً!", statusPaidMsg: "شكراً لك، نتمنى أن تستمتع بالوجبة! 😋", welcomeTitle: "أهلاً بك في مطعمنا!", welcomeDesc: "استمتع بتجربة طعام فريدة مع قائمة مختارة بعناية. نحن هنا لنقدم لك أطيب المأكولات، اطلب ما تشاء وسنحضره إليك بكل حب.", exploreMenuBtn: "استعرض قائمة الطعام", receipts: "فواتيري", addToExistingOrder: "إضافة إلى الطلب", currency: "د.ج",
    orderSubmitting: "جاري إرسال الطلب…", orderSuccess: "تم تأكيد طلبك بنجاح.", orderNumber: "رقم الطلب", orderEmptyCart: "السلة فارغة. أضف وجبة واحدة على الأقل.", orderDeliveryRequired: "يرجى إكمال بيانات التوصيل قبل التأكيد.", orderAuthError: "تعذر التحقق من جلسة الزبون. يرجى المحاولة مرة أخرى.", orderNetworkError: "تعذر الاتصال بالخادم. لم يتم حذف السلة؛ يمكنك المحاولة مرة أخرى.", orderValidationError: "بيانات الطلب غير صالحة. راجع السلة وحاول مرة أخرى.", orderServerRejection: "تعذر قبول الطلب من الخادم. لم يتم حذف السلة؛ يرجى المحاولة مرة أخرى.", orderGenericError: "حدث خطأ أثناء إرسال الطلب. لم يتم حذف السلة؛ يمكنك المحاولة مرة أخرى.", discount: "خصم"
  },
  fr: {
    appName: "MenuFlow", table: "Table n°", welcomeMessage: "Bienvenue dans notre restaurant !", all: "Tous", burgers: "Burgers", pizza: "Pizzas", appetizers: "Entrées", salads: "Salades", main: "Plats principaux", desserts: "Desserts", drinks: "Boissons", specialNote: "Note spéciale sur le plat...", addToCart: "Ajouter au panier", checkout: "Passer la commande", deliveryDetails: "Détails de livraison", enterCustomerName: "Nom complet / Titre de la commande", enterAddress: "Adresse détaillée", enterPhone: "Numéro de téléphone", confirmOrder: "Confirmer la commande", aiAssistantTitle: "Assistant intelligent MenuFlow", aiInputPlaceholder: "Les ingrédients sont-ils naturels ? Posez votre question...", send: "Envoyer", aiErrorMessage: "Désolé, une erreur s'est produite lors de la connexion.", currentOrderStatus: "Statut actuel de la commande", howWasExperience: "Comment s'est passée votre expérience ?", yourFeedback: "Rédigez vos remarques et votre évaluation ici...", sendReview: "Envoyer l'évaluation", thankYouReview: "Merci ! Votre avis a été reçu avec succès.", stagePending: "Reçue", stagePreparing: "Préparation", stageReady: "Prêt", stagePaid: "Payé", statusPendingMsg: "Votre commande a été reçue avec succès !", statusPreparingMsg: "Votre commande est en cours de préparation... 👨‍🍳", statusReadyMsg: "Votre commande est totalement prête !", statusPaidMsg: "Merci ! Nous espérons que vous apprécierez votre repas ! 😋", welcomeTitle: "Bienvenue dans notre restaurant !", welcomeDesc: "Profitez d'une expérience culinaire unique avec un menu soigneusement sélectionné. Nous sommes là pour vous servir de délicieux plats.", exploreMenuBtn: "Parcourir le menu", addToExistingOrder: "Ajouter à la commande", currency: "DZD", receipts: "Mes reçus",
    orderSubmitting: "Envoi de la commande…", orderSuccess: "Votre commande a été confirmée.", orderNumber: "Numéro de commande", orderEmptyCart: "Le panier est vide. Ajoutez au moins un article.", orderDeliveryRequired: "Veuillez compléter les informations de livraison avant de confirmer.", orderAuthError: "Impossible de vérifier votre session. Veuillez réessayer.", orderNetworkError: "Connexion au serveur impossible. Votre panier est conservé ; vous pouvez réessayer.", orderValidationError: "Les données de la commande sont invalides. Vérifiez votre panier et réessayez.", orderServerRejection: "Le serveur n'a pas accepté la commande. Votre panier est conservé ; veuillez réessayer.", orderGenericError: "Une erreur s'est produite. Votre panier est conservé ; vous pouvez réessayer.", discount: "Remise"
  },
  en: {
    appName: "MenuFlow", table: "Table No.", welcomeMessage: "Welcome to our restaurant!", all: "All", burgers: "Burgers", pizza: "Pizza", appetizers: "Appetizers", salads: "Salads", main: "Main Courses", desserts: "Desserts", drinks: "Drinks", specialNote: "Special note on meal...", addToCart: "Add to Cart", checkout: "Checkout", deliveryDetails: "Delivery Details", enterCustomerName: "Full Name / Order Title", enterAddress: "Detailed Address", enterPhone: "Phone Number", confirmOrder: "Confirm Order", aiAssistantTitle: "MenuFlow Smart Assistant", aiInputPlaceholder: "Are ingredients natural? Ask AI...", send: "Send", aiErrorMessage: "Sorry, an error occurred while contacting assistant.", currentOrderStatus: "Current Order Status", howWasExperience: "How was your experience with us?", yourFeedback: "Write your feedback & rating here...", sendReview: "Submit Review", thankYouReview: "Thank you! Your feedback has been received.", stagePending: "Received", stagePreparing: "Preparing", stageReady: "Ready", stagePaid: "Paid", statusPendingMsg: "Your order has been received successfully!", statusPreparingMsg: "Preparing your delicious meal... 👨‍🍳", statusReadyMsg: "Your order is fully ready!", statusPaidMsg: "Thank you! We hope you enjoy your meal! 😋", welcomeTitle: "Welcome to our restaurant!", welcomeDesc: "Enjoy a unique dining experience with a carefully selected menu. We are here to serve you the finest food, order whatever you like.", exploreMenuBtn: "Explore Menu", addToExistingOrder: "Add to Order", currency: "DA", receipts: "My receipts",
    orderSubmitting: "Submitting order…", orderSuccess: "Your order has been confirmed.", orderNumber: "Order number", orderEmptyCart: "Your cart is empty. Add at least one item.", orderDeliveryRequired: "Please complete the delivery details before confirming.", orderAuthError: "We could not verify your customer session. Please try again.", orderNetworkError: "Could not reach the server. Your cart was kept; you can try again.", orderValidationError: "The order data is invalid. Review your cart and try again.", orderServerRejection: "The server rejected the order. Your cart was kept; please try again.", orderGenericError: "Something went wrong while submitting the order. Your cart was kept; you can try again.", discount: "Discount"
  }
};
